### ISSUE TITLE
CaroloCup Todo

### ISSUE THREAD

**Issue by fabolhak** [lms-org/config_auto_drive#122]
- [x] check if camera calibration is correct
- [x] document and understand parameter
- [x] adapt parking module to new parking mode
- [x] check if we can change mode on electronic firmware via config parameter
- [x] detect startline
